cmake_minimum_required(VERSION 3.5)
project(VectorLib)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(DEFINED REAL_PRECISION)
    add_compile_definitions(REAL_PRECISION=${REAL_PRECISION})
endif()
add_subdirectory(ext/doctest)
add_subdirectory(tests)
